import { hostname as osHostname } from 'node:os'
import { writeFile, access } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { loadConfig } from './config-loader.js'
import { evaluateAgent } from './checks.js'
import { startWatch } from './watch.js'
import { login } from './login.js'
import { runSetup } from './setup.js'
import { assertSupportedPlatform } from './platform.js'
import type { Handlers, CommandOpts } from './cli.js'

// All Pulse endpoints are served under /api/pulse on the ingest host.
const INGEST_ORIGIN = 'https://ingest.waydock.ai'
export const DEFAULT_INGEST_BASE = `${INGEST_ORIGIN}/api/pulse` // login posts to ${base}/oauth/...
export const DEFAULT_HEARTBEAT_URL = `${DEFAULT_INGEST_BASE}/heartbeat`

// ---------------------------------------------------------------------------
// Load the config or exit. A missing file is the common first-run case, so point
// the user at `pulse init` instead of surfacing a raw ENOENT.
// ---------------------------------------------------------------------------
export async function loadConfigOrExit(
  configPath: string,
): Promise<Awaited<ReturnType<typeof loadConfig>>> {
  try {
    return await loadConfig(configPath)
  } catch (err: any) {
    if (err?.code === 'ENOENT') {
      process.stderr.write(
        `No config file found at ${configPath}.\n` +
        'Run `pulse init` to create one, then edit it and try again.\n',
      )
    } else {
      process.stderr.write(`Error loading config: ${err.message}\n`)
    }
    process.exit(1)
  }
}

// ---------------------------------------------------------------------------
// check — read-only: evaluate all agents and print a table, no restart, no POST
// ---------------------------------------------------------------------------
async function check(opts: { config: string; json?: boolean }): Promise<void> {
  assertSupportedPlatform()
  const config = await loadConfigOrExit(opts.config)

  const results = await Promise.all(
    config.agents.map(async agent => ({
      name: agent.name,
      up: await evaluateAgent(agent.checks),
    })),
  )

  if (opts.json) {
    process.stdout.write(JSON.stringify({ node: config.node, agents: results }) + '\n')
    return
  }

  // Print table
  const nameWidth = Math.max(4, ...results.map(r => r.name.length))
  process.stdout.write(`${'NAME'.padEnd(nameWidth)}  STATUS\n`)
  process.stdout.write(`${'-'.repeat(nameWidth)}  ------\n`)
  for (const { name, up } of results) {
    process.stdout.write(`${name.padEnd(nameWidth)}  ${up ? 'up' : 'down'}\n`)
  }
}

// ---------------------------------------------------------------------------
// start — load config, validate key, then startWatch
// ---------------------------------------------------------------------------
async function start(opts: { config: string; quiet?: boolean }): Promise<void> {
  assertSupportedPlatform()
  const config = await loadConfigOrExit(opts.config)

  if (!config.heartbeat.key) {
    process.stderr.write(
      'No heartbeat key found. Run `pulse login` first to authenticate this machine.\n',
    )
    process.exit(1)
  }

  // Startup summary so the foreground watcher doesn't look frozen: what it's
  // watching, how often it beats, where to, and how to stop it.
  let host: string
  try { host = new URL(config.heartbeat.url).host } catch { host = config.heartbeat.url }
  const n = config.agents.length
  process.stdout.write(
    `Starting Pulse watch on node "${config.node}" — ` +
    `${n} agent${n === 1 ? '' : 's'}, heartbeat every ${config.heartbeat.interval}s → ${host}.\n` +
    'Running in the foreground; press Ctrl+C to stop' +
    (opts.quiet ? '.\n' : ' (use --quiet to silence per-beat status).\n'),
  )

  // Per-beat status line so you can see it's alive — suppressed with --quiet.
  const stop = await startWatch(config, {
    onHeartbeat: opts.quiet ? undefined : ({ ok, up, down }) => {
      const t = new Date().toTimeString().slice(0, 8)
      process.stdout.write(
        `[${t}] heartbeat ${ok ? 'ok' : 'FAILED'} · ${up} up${down ? ` · ${down} down` : ''}\n`,
      )
    },
  })

  // Handle graceful shutdown
  const shutdown = () => {
    process.stdout.write('\nStopping Pulse...\n')
    stop()
    process.exit(0)
  }
  process.on('SIGINT', shutdown)
  process.on('SIGTERM', shutdown)

  // Block forever (the loops are independent timers)
  await new Promise<void>(() => {})
}

// ---------------------------------------------------------------------------
// init — write a starter pulse.config.yaml if absent
// ---------------------------------------------------------------------------
export const STARTER_CONFIG = `# pulse.config.yaml — generated by \`pulse init\`
# Docs: https://waydock.ai/docs/pulse

node: my-server          # unique name for this machine

heartbeat:
  url: ${DEFAULT_HEARTBEAT_URL}
  # key is loaded from ~/.pulse/credentials.json after \`pulse login\`
  interval: 60           # seconds between heartbeats

defaults:
  retries: 3             # restart attempts before giving up
  confirm: 2             # consecutive failures before marking down

agents:
  - name: my-process
    checks:
      - process: my-process-name   # checks ps output for this string
    # Optional: restart command (e.g. launchd on macOS)
    # restart: launchctl kickstart -k gui/$(id -u)/com.example.myservice
`

// Decide whether `pulse init` should run the guided wizard. Explicit flags win;
// otherwise it's guided only when both ends are an interactive terminal (so CI,
// pipes, and `pulse init >file` keep the predictable static-template behaviour).
export function shouldRunWizard(
  opts: Pick<CommandOpts, 'interactive' | 'yes'>,
  tty: { stdin?: boolean; stdout?: boolean },
): boolean {
  if (opts.interactive) return true
  if (opts.yes) return false
  return Boolean(tty.stdin && tty.stdout)
}

async function init(opts: CommandOpts): Promise<void> {
  assertSupportedPlatform()
  if (shouldRunWizard(opts, { stdin: process.stdin.isTTY, stdout: process.stdout.isTTY })) {
    return runSetup({ config: opts.config })
  }

  const configPath = resolve(opts.config)

  // Refuse to overwrite an existing file
  try {
    await access(configPath)
    process.stderr.write(
      `Config file already exists: ${configPath}\nRemove it first if you want to regenerate.\n`,
    )
    process.exit(1)
  } catch {
    // File doesn't exist — proceed
  }

  try {
    const { mkdir } = await import('node:fs/promises')
    await mkdir(dirname(configPath), { recursive: true })
    await writeFile(configPath, STARTER_CONFIG, 'utf8')
    process.stdout.write(`Created ${configPath}\nEdit it, then run \`pulse start\`.\n`)
  } catch (err: any) {
    process.stderr.write(`Error writing config: ${err.message}\n`)
    process.exit(1)
  }
}

// ---------------------------------------------------------------------------
// login — device-flow auth against the default ingest base
// ---------------------------------------------------------------------------
async function loginCmd(opts: { config: string }): Promise<void> {
  try {
    await login({
      base: DEFAULT_INGEST_BASE,
      hostname: osHostname(),
    })
    process.stdout.write(
      'Logged in successfully.\n\n' +
      'Next steps:\n' +
      '  pulse init     create pulse.config.yaml (skip if you already have one)\n' +
      '  pulse start    run the watcher\n\n' +
      'Tip: if you ran this via npx, prefix each command — e.g. `npx @waydock/pulse start`.\n',
    )
  } catch (err: any) {
    process.stderr.write(`Login failed: ${err.message}\n`)
    process.exit(1)
  }
}

// ---------------------------------------------------------------------------
// status — what the running watcher last saw (from the persisted state file)
// ---------------------------------------------------------------------------
async function statusCmd(opts: CommandOpts): Promise<void> {
  const { readStatus, formatStatus } = await import('./status.js')
  const info = await readStatus({ configPath: opts.config })
  if (opts.json) {
    process.stdout.write(JSON.stringify(info) + '\n')
    return
  }
  process.stdout.write(formatStatus(info))
}

// ---------------------------------------------------------------------------
// logs — tail the service log file
// ---------------------------------------------------------------------------
async function logsCmd(opts: CommandOpts): Promise<void> {
  const { runLogs } = await import('./logs.js')
  await runLogs({ follow: opts.follow, lines: opts.lines })
}

// ---------------------------------------------------------------------------
// logout / whoami
// ---------------------------------------------------------------------------
async function logoutCmd(_opts: CommandOpts): Promise<void> {
  const { logout } = await import('./account.js')
  const { removed, path } = await logout()
  process.stdout.write(removed ? `Logged out (removed ${path}).\n` : 'Not logged in.\n')
}

async function whoamiCmd(opts: CommandOpts): Promise<void> {
  const { readWhoami, formatWhoami } = await import('./account.js')
  const info = await readWhoami({ configPath: opts.config })
  process.stdout.write(formatWhoami(info) + '\n')
}

// ---------------------------------------------------------------------------
// doctor — preflight diagnostics
// ---------------------------------------------------------------------------
async function doctorCmd(opts: CommandOpts): Promise<void> {
  assertSupportedPlatform()
  const { runDoctor, formatReport } = await import('./doctor.js')
  const report = await runDoctor({ configPath: opts.config })
  process.stdout.write(formatReport(report))
  if (!report.ok) process.exit(1)
}

// ---------------------------------------------------------------------------
// install / uninstall — register Pulse as a background service
// ---------------------------------------------------------------------------
async function installCmd(opts: CommandOpts): Promise<void> {
  const { performInstall } = await import('./service.js')
  const result = await performInstall(opts.config)
  for (const m of result.messages) process.stdout.write(m + '\n')
  if (!result.installed) process.exit(1)
}

async function uninstallCmd(opts: CommandOpts): Promise<void> {
  const { performUninstall } = await import('./service.js')
  const result = await performUninstall(opts.config)
  for (const m of result.messages) process.stdout.write(m + '\n')
}

// ---------------------------------------------------------------------------
// upgrade / version / help
// ---------------------------------------------------------------------------
async function upgradeCmd(_opts: CommandOpts): Promise<void> {
  const { upgrade } = await import('./upgrade.js')
  const code = await upgrade()
  if (code !== 0) process.exit(code)
}

async function versionCmd(_opts: CommandOpts): Promise<void> {
  const { getVersion } = await import('./version.js')
  process.stdout.write(`${await getVersion()}\n`)
}

async function helpCmd(_opts: CommandOpts): Promise<void> {
  process.stdout.write(HELP_TEXT)
}

export const HELP_TEXT = `pulse — open-source watcher CLI

Usage: pulse <command> [options]

Commands:
  init        Set up pulse.config.yaml (guided wizard on a terminal; --yes for the static template)
  login       Authenticate this machine (device flow)
  logout      Remove stored credentials
  whoami      Show authentication status for this machine
  check       Evaluate all agents once and print status (--json for machine-readable output)
  status      Show what the running watcher last saw (from the persisted state file)
  logs        Tail the service log (--follow to stream, --lines N for how many)
  start       Run the watch + heartbeat loops in the foreground (--quiet to silence per-beat status)
  doctor      Run preflight diagnostics
  install     Run Pulse as a background service (launchd/systemd)
  uninstall   Remove the background service
  upgrade     Update to the latest published version
  version     Print the CLI version
  help        Show this help

Options:
  --config <path>   Config file (default: ./pulse.config.yaml)
  -i, --interactive Force the guided wizard (init)
  -y, --yes         Use the static template (init)
  -q, --quiet       Silence per-heartbeat status (start)
  --json            Machine-readable output (check, status)
  -f, --follow      Stream new log lines (logs)
  -n, --lines <n>   How many log lines to show (logs, default 50)
  -v, --version     Print version
`

// ---------------------------------------------------------------------------
// Export as the real defaultHandlers shape
// ---------------------------------------------------------------------------
export const commands: Handlers = {
  init,
  check,
  status: statusCmd,
  logs: logsCmd,
  start,
  login: loginCmd,
  logout: logoutCmd,
  whoami: whoamiCmd,
  doctor: doctorCmd,
  install: installCmd,
  uninstall: uninstallCmd,
  upgrade: upgradeCmd,
  version: versionCmd,
  help: helpCmd,
}
