import { hostname as osHostname } from 'node:os'
import { writeFile, access } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { loadConfig } from './config-loader.js'
import { evaluateAgent } from './checks.js'
import { startWatch } from './watch.js'
import { login } from './login.js'
import type { Handlers } from './cli.js'

const DEFAULT_INGEST_BASE = 'https://ingest.waydock.ai'

// ---------------------------------------------------------------------------
// check — read-only: evaluate all agents and print a table, no restart, no POST
// ---------------------------------------------------------------------------
async function check(opts: { config: string }): Promise<void> {
  let config
  try {
    config = await loadConfig(opts.config)
  } catch (err: any) {
    process.stderr.write(`Error loading config: ${err.message}\n`)
    process.exit(1)
  }

  const results = await Promise.all(
    config.agents.map(async agent => ({
      name: agent.name,
      up: await evaluateAgent(agent.checks),
    })),
  )

  // Print table
  const nameWidth = Math.max(4, ...results.map(r => r.name.length))
  process.stdout.write(`${'NAME'.padEnd(nameWidth)}  STATUS\n`)
  process.stdout.write(`${'-'.repeat(nameWidth)}  ------\n`)
  for (const { name, up } of results) {
    process.stdout.write(`${name.padEnd(nameWidth)}  ${up ? 'up' : 'down'}\n`)
  }
}

// ---------------------------------------------------------------------------
// start — load config, validate key, then startWatch
// ---------------------------------------------------------------------------
async function start(opts: { config: string }): Promise<void> {
  let config
  try {
    config = await loadConfig(opts.config)
  } catch (err: any) {
    process.stderr.write(`Error loading config: ${err.message}\n`)
    process.exit(1)
  }

  if (!config.heartbeat.key) {
    process.stderr.write(
      'No heartbeat key found. Run `pulse login` first to authenticate this machine.\n',
    )
    process.exit(1)
  }

  process.stdout.write(`Starting Pulse watch on node "${config.node}"...\n`)
  const stop = startWatch(config)

  // Handle graceful shutdown
  const shutdown = () => {
    process.stdout.write('\nStopping Pulse...\n')
    stop()
    process.exit(0)
  }
  process.on('SIGINT', shutdown)
  process.on('SIGTERM', shutdown)

  // Block forever (the loops are independent timers)
  await new Promise<void>(() => {})
}

// ---------------------------------------------------------------------------
// init — write a starter pulse.config.yaml if absent
// ---------------------------------------------------------------------------
const STARTER_CONFIG = `# pulse.config.yaml — generated by \`pulse init\`
# Docs: https://docs.waydock.ai/pulse

node: my-server          # unique name for this machine

heartbeat:
  url: https://ingest.waydock.ai/v1/heartbeat
  # key is loaded from ~/.pulse/credentials.json after \`pulse login\`
  interval: 60           # seconds between heartbeats

defaults:
  retries: 3             # restart attempts before giving up
  confirm: 2             # consecutive failures before marking down

agents:
  - name: my-process
    checks:
      - process: my-process-name   # checks ps output for this string
    # Optional: restart command (e.g. launchd on macOS)
    # restart: launchctl kickstart -k gui/$(id -u)/com.example.myservice
`

async function init(opts: { config: string }): Promise<void> {
  const configPath = resolve(opts.config)

  // Refuse to overwrite an existing file
  try {
    await access(configPath)
    process.stderr.write(
      `Config file already exists: ${configPath}\nRemove it first if you want to regenerate.\n`,
    )
    process.exit(1)
  } catch {
    // File doesn't exist — proceed
  }

  try {
    const { mkdir } = await import('node:fs/promises')
    await mkdir(dirname(configPath), { recursive: true })
    await writeFile(configPath, STARTER_CONFIG, 'utf8')
    process.stdout.write(`Created ${configPath}\nEdit it, then run \`pulse start\`.\n`)
  } catch (err: any) {
    process.stderr.write(`Error writing config: ${err.message}\n`)
    process.exit(1)
  }
}

// ---------------------------------------------------------------------------
// login — device-flow auth against the default ingest base
// ---------------------------------------------------------------------------
async function loginCmd(opts: { config: string }): Promise<void> {
  try {
    await login({
      base: DEFAULT_INGEST_BASE,
      hostname: osHostname(),
    })
    process.stdout.write('Logged in successfully. You can now run `pulse start`.\n')
  } catch (err: any) {
    process.stderr.write(`Login failed: ${err.message}\n`)
    process.exit(1)
  }
}

// ---------------------------------------------------------------------------
// Export as the real defaultHandlers shape
// ---------------------------------------------------------------------------
export const commands: Handlers = {
  init,
  check,
  start,
  login: loginCmd,
}
