import { createInterface, type Interface } from 'node:readline/promises'
import { writeFile, access, mkdir } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { hostname as osHostname } from 'node:os'
import { Config } from '@waydock/pulse-core'
import { DEFAULT_HEARTBEAT_URL } from './commands.js'

// ---------------------------------------------------------------------------
// Guided setup ("pulse init" on a TTY). The flow is intentionally split so it
// stays testable: the pure answer->YAML mapping has no I/O, and the prompt loop
// talks to an injectable `Prompter` so a scripted fake can drive it in tests.
// ---------------------------------------------------------------------------

export type CheckAnswer =
  | { kind: 'process'; value: string }
  | { kind: 'http'; value: string }
  | { kind: 'command'; value: string }

export type AgentAnswer = {
  name: string
  check: CheckAnswer
  restart: string | false // false => alert-only (no restart command)
}

export type SetupAnswers = {
  node: string
  interval: number
  agents: AgentAnswer[]
  webhookUrl?: string
}

// ---------------------------------------------------------------------------
// Restart-command suggestions. The static template only ever showed a macOS
// launchctl line, which is wrong on Linux; offer the right shape per platform.
// ---------------------------------------------------------------------------
export function restartTemplateFor(platform: NodeJS.Platform, name: string): string {
  if (platform === 'darwin') {
    return `launchctl kickstart -k gui/$(id -u)/com.example.${name}`
  }
  // linux + everything else: systemd is the overwhelmingly common case
  return `systemctl restart ${name}`
}

// ---------------------------------------------------------------------------
// YAML scalar quoting. Most answers (names, urls, simple commands) are valid
// plain scalars, but restart/command/process strings can contain spaces, `$`,
// `:` etc. Emit a plain scalar when it's unambiguous, else a double-quoted one
// (JSON.stringify produces a valid YAML double-quoted scalar for our cases).
// ---------------------------------------------------------------------------
export function yamlScalar(s: string): string {
  // Plain only when it's a tame token and can't be read as a number/bool/null,
  // doesn't start with an indicator char, and has no `: ` or trailing space.
  const tame = /^[A-Za-z0-9_./@:+-]+$/.test(s)
  const looksTyped = /^(true|false|null|yes|no|on|off|~|-?\d+(\.\d+)?)$/i.test(s)
  const startsBad = /^[-?:,[\]{}#&*!|>'"%@`]/.test(s)
  if (tame && !looksTyped && !startsBad && !s.includes(': ')) return s
  return JSON.stringify(s)
}

function checkLine(check: CheckAnswer): string {
  return `      - ${check.kind}: ${yamlScalar(check.value)}`
}

// ---------------------------------------------------------------------------
// Pure: turn collected answers into a commented pulse.config.yaml. We hand-roll
// the YAML (rather than js-yaml dump) so the generated file keeps the same
// teaching comments as the static template and stays hand-editable afterward.
// ---------------------------------------------------------------------------
export function buildConfigYaml(
  answers: SetupAnswers,
  heartbeatUrl: string = DEFAULT_HEARTBEAT_URL,
): string {
  const lines: string[] = [
    '# pulse.config.yaml — generated by `pulse init`',
    '# Docs: https://docs.waydock.ai/pulse',
    '',
    `node: ${yamlScalar(answers.node)}          # unique name for this machine`,
    '',
    'heartbeat:',
    `  url: ${heartbeatUrl}`,
    '  # key is loaded from ~/.pulse/credentials.json after `pulse login`',
    `  interval: ${answers.interval}           # seconds between heartbeats`,
    '',
    'defaults:',
    '  retries: 3             # restart attempts before giving up',
    '  confirm: 2             # consecutive failures before marking down',
    '',
  ]

  if (answers.webhookUrl) {
    lines.push(
      '# Local alert webhook (Discord webhook URLs are auto-detected)',
      'webhook:',
      `  url: ${answers.webhookUrl}`,
      '',
    )
  }

  lines.push('agents:')
  for (const agent of answers.agents) {
    lines.push(`  - name: ${yamlScalar(agent.name)}`)
    lines.push('    checks:')
    lines.push(checkLine(agent.check))
    if (agent.restart === false) {
      lines.push('    # alert-only: Pulse reports it down but runs no restart command')
    } else {
      lines.push(`    restart: ${yamlScalar(agent.restart)}`)
    }
  }

  return lines.join('\n') + '\n'
}

// ---------------------------------------------------------------------------
// Validate the answers by round-tripping through the real zod schema before we
// ever write a file, so "guided" can never produce a config that `pulse start`
// would reject. Throws the zod error if something is off.
// ---------------------------------------------------------------------------
export function validateAnswers(answers: SetupAnswers, heartbeatUrl: string = DEFAULT_HEARTBEAT_URL): void {
  Config.parse({
    node: answers.node,
    heartbeat: { url: heartbeatUrl, interval: answers.interval },
    ...(answers.webhookUrl ? { webhook: { url: answers.webhookUrl } } : {}),
    agents: answers.agents.map(a => ({
      name: a.name,
      checks: [{ [a.check.kind]: a.check.value }],
      ...(a.restart === false ? { restart: false } : { restart: a.restart }),
    })),
  })
}

// ---------------------------------------------------------------------------
// Prompter — the thin interactive surface the wizard depends on. Implemented
// over readline for the real CLI; faked in tests.
// ---------------------------------------------------------------------------
export type SelectOption<T> = { value: T; label: string; hint?: string }

export interface Prompter {
  intro(title: string): void
  note(msg: string): void
  text(opts: {
    message: string
    default?: string
    validate?: (v: string) => string | undefined
  }): Promise<string>
  select<T>(opts: { message: string; options: SelectOption<T>[]; initial?: number }): Promise<T>
  confirm(opts: { message: string; default?: boolean }): Promise<boolean>
  outro(msg: string): void
  close(): void
}

// ANSI helpers — colour only on a real TTY and when NO_COLOR is unset.
const useColor = process.env.NO_COLOR == null && Boolean(process.stdout.isTTY)
const paint = (code: string) => (s: string) => (useColor ? `\x1b[${code}m${s}\x1b[0m` : s)
const dim = paint('2')
const bold = paint('1')
const cyan = paint('36')
const green = paint('32')
const red = paint('31')

const GUTTER = dim('│')

export class CancelledError extends Error {
  constructor() {
    super('cancelled')
    this.name = 'CancelledError'
  }
}

// A buffered line reader. We deliberately avoid readline's `question()`: in
// flowing mode (a piped stdin) every line fires before the next question is
// registered, so the answers get dropped. Buffering lines as they arrive — and
// parking a waiter when the queue is empty — works identically for a live TTY
// and a pipe. `next()` resolves to null at EOF / Ctrl-C so callers can cancel.
function createLineReader(input: NodeJS.ReadableStream): { next: () => Promise<string | null>; close: () => void } {
  const rl: Interface = createInterface({ input })
  const queue: string[] = []
  const waiters: Array<(line: string | null) => void> = []
  let closed = false

  rl.on('line', line => {
    const w = waiters.shift()
    if (w) w(line)
    else queue.push(line)
  })
  rl.on('close', () => {
    closed = true
    while (waiters.length) waiters.shift()!(null)
  })

  return {
    next() {
      if (queue.length) return Promise.resolve(queue.shift()!)
      if (closed) return Promise.resolve(null)
      return new Promise(res => waiters.push(res))
    },
    close: () => rl.close(),
  }
}

// ---------------------------------------------------------------------------
// Readline-backed prompter with a light clack-style gutter. No raw-mode arrow
// navigation — selects are a numbered menu, which is robust, accessible, and
// doesn't fight terminals. EOF / Ctrl-C raise CancelledError so the wizard can
// bow out cleanly instead of dumping a stack trace.
// ---------------------------------------------------------------------------
export function createReadlinePrompter(): Prompter {
  const reader = createLineReader(process.stdin)

  const ask = async (prompt: string): Promise<string> => {
    process.stdout.write(prompt)
    const line = await reader.next()
    if (line === null) throw new CancelledError()
    return line
  }

  const write = (s: string) => process.stdout.write(s)

  return {
    intro(title) {
      write(`\n${cyan('◆')}  ${bold(title)}\n${GUTTER}\n`)
    },
    note(msg) {
      for (const line of msg.split('\n')) write(`${GUTTER}  ${dim(line)}\n`)
    },
    async text({ message, default: def, validate }) {
      for (;;) {
        const hint = def ? dim(` (${def})`) : ''
        const answer = (await ask(`${cyan('◇')}  ${message}${hint}\n${GUTTER}  ${dim('›')} `)).trim()
        const value = answer === '' && def !== undefined ? def : answer
        const err = validate?.(value)
        if (err) {
          write(`${red('▲')}  ${err}\n`)
          continue
        }
        return value
      }
    },
    async select({ message, options, initial = 0 }) {
      write(`${cyan('◇')}  ${message}\n`)
      options.forEach((o, i) => {
        const marker = i === initial ? cyan('●') : dim('○')
        const hint = o.hint ? dim(`  — ${o.hint}`) : ''
        write(`${GUTTER}  ${marker} ${i + 1}. ${o.label}${hint}\n`)
      })
      for (;;) {
        const raw = (await ask(`${GUTTER}  ${dim('›')} `)).trim()
        const idx = raw === '' ? initial : Number(raw) - 1
        if (Number.isInteger(idx) && idx >= 0 && idx < options.length) return options[idx].value
        write(`${red('▲')}  Enter a number between 1 and ${options.length}.\n`)
      }
    },
    async confirm({ message, default: def = true }) {
      const hint = def ? 'Y/n' : 'y/N'
      for (;;) {
        const raw = (await ask(`${cyan('◇')}  ${message} ${dim(`(${hint})`)}\n${GUTTER}  ${dim('›')} `)).trim().toLowerCase()
        if (raw === '') return def
        if (['y', 'yes'].includes(raw)) return true
        if (['n', 'no'].includes(raw)) return false
        write(`${red('▲')}  Please answer y or n.\n`)
      }
    },
    outro(msg) {
      write(`${GUTTER}\n${green('◆')}  ${msg}\n\n`)
    },
    close() {
      reader.close()
    },
  }
}

// ---------------------------------------------------------------------------
// The wizard flow. Pure with respect to I/O — everything goes through `p`.
// ---------------------------------------------------------------------------
const nonEmpty = (label: string) => (v: string) => (v.trim() === '' ? `${label} can't be empty.` : undefined)
const validUrl = (v: string) => {
  try {
    new URL(v)
    return undefined
  } catch {
    return 'Enter a valid URL (including http:// or https://).'
  }
}

export async function collectAnswers(
  p: Prompter,
  env: { hostname: string; platform: NodeJS.Platform },
): Promise<SetupAnswers> {
  p.intro('Pulse setup')
  p.note('Answer a few questions and Pulse writes a ready-to-run pulse.config.yaml.\nPress Enter to accept the [default] in parentheses.')

  const node = await p.text({
    message: 'Name for this machine',
    default: env.hostname,
    validate: nonEmpty('Name'),
  })

  const interval = await p.select<number>({
    message: 'How often should it check in (heartbeat + checks)?',
    options: [
      { value: 30, label: 'Every 30 seconds', hint: 'snappy' },
      { value: 60, label: 'Every 60 seconds', hint: 'recommended' },
      { value: 300, label: 'Every 5 minutes', hint: 'low-traffic' },
    ],
    initial: 1,
  })

  const agents: AgentAnswer[] = []
  do {
    p.note(agents.length === 0 ? "Now let's add something to watch." : 'Add another thing to watch.')

    const name = await p.text({ message: 'What do you want to watch? (short name)', validate: nonEmpty('Name') })

    const kind = await p.select<CheckAnswer['kind']>({
      message: 'How should Pulse tell if it’s alive?',
      options: [
        { value: 'process', label: 'A process is running', hint: 'matches `ps` output' },
        { value: 'http', label: 'An HTTP endpoint returns 2xx', hint: 'health check URL' },
        { value: 'command', label: 'A command exits 0', hint: 'e.g. systemctl is-active' },
      ],
    })

    let check: CheckAnswer
    if (kind === 'process') {
      const value = await p.text({ message: 'Process name to look for', default: name, validate: nonEmpty('Process name') })
      check = { kind, value }
    } else if (kind === 'http') {
      const value = await p.text({ message: 'Health check URL', default: 'http://localhost:8080/health', validate: validUrl })
      check = { kind, value }
    } else {
      const value = await p.text({ message: 'Command to run', default: `systemctl is-active ${name}`, validate: nonEmpty('Command') })
      check = { kind, value }
    }

    const recovery = await p.select<'restart' | 'alert'>({
      message: 'If it goes down, what should Pulse do?',
      options: [
        { value: 'restart', label: 'Run a restart command', hint: 'auto-recover' },
        { value: 'alert', label: 'Just alert me', hint: 'no restart' },
      ],
    })

    let restart: string | false = false
    if (recovery === 'restart') {
      restart = await p.text({
        message: 'Restart command',
        default: restartTemplateFor(env.platform, name),
        validate: nonEmpty('Restart command'),
      })
    }

    agents.push({ name, check, restart })
  } while (await p.confirm({ message: 'Add another agent?', default: false }))

  let webhookUrl: string | undefined
  if (await p.confirm({ message: 'Send alerts to a webhook (e.g. Discord)?', default: false })) {
    webhookUrl = await p.text({ message: 'Webhook URL', validate: validUrl })
  }

  return { node, interval, agents, webhookUrl }
}

// ---------------------------------------------------------------------------
// runSetup — the real command entry: drive the wizard, validate, write the file
// (asking before clobbering an existing one), and print next steps.
// ---------------------------------------------------------------------------
export async function runSetup(opts: { config: string }): Promise<void> {
  const configPath = resolve(opts.config)
  const p = createReadlinePrompter()

  try {
    const exists = await access(configPath).then(() => true, () => false)
    const answers = await collectAnswers(p, { hostname: osHostname(), platform: process.platform })

    validateAnswers(answers)
    const yaml = buildConfigYaml(answers)

    if (exists) {
      const overwrite = await p.confirm({
        message: `${configPath} already exists. Overwrite it?`,
        default: false,
      })
      if (!overwrite) {
        p.outro('Left your existing config untouched.')
        return
      }
    }

    await mkdir(dirname(configPath), { recursive: true })
    await writeFile(configPath, yaml, 'utf8')

    p.note(`Wrote ${configPath}:\n\n${yaml}`)
    p.outro(
      'Next steps:\n' +
        '  pulse login    authenticate this machine\n' +
        '  pulse check    dry-run your checks (no restarts, no network)\n' +
        '  pulse start    run the watcher',
    )
  } catch (err) {
    if (err instanceof CancelledError) {
      process.stdout.write('\nSetup cancelled. No changes made.\n')
      return
    }
    throw err
  } finally {
    p.close()
  }
}
