import { describe, it, expect } from 'vitest'
import { load as parseYaml } from 'js-yaml'
import { Config } from '@waydock/pulse-core'
import {
  buildConfigYaml,
  restartTemplateFor,
  yamlScalar,
  validateAnswers,
  collectAnswers,
  runPostSetup,
  type SetupAnswers,
  type Prompter,
  type SelectOption,
} from './setup.js'

const HB = 'https://ingest.waydock.ai/api/pulse/heartbeat'

describe('restartTemplateFor', () => {
  it('suggests launchctl on macOS and systemctl elsewhere', () => {
    expect(restartTemplateFor('darwin', 'web')).toContain('launchctl')
    expect(restartTemplateFor('darwin', 'web')).toContain('com.example.web')
    expect(restartTemplateFor('linux', 'web')).toBe('systemctl restart web')
    expect(restartTemplateFor('win32', 'web')).toBe('systemctl restart web')
  })
})

describe('yamlScalar', () => {
  it('leaves tame tokens and URLs unquoted', () => {
    expect(yamlScalar('my-host')).toBe('my-host')
    expect(yamlScalar('http://localhost:8080/health')).toBe('http://localhost:8080/health')
  })
  it('quotes values with spaces or shell metacharacters', () => {
    expect(yamlScalar('systemctl restart web')).toBe('"systemctl restart web"')
    expect(yamlScalar('launchctl kickstart -k gui/$(id -u)/com.example.web')).toContain('"')
  })
  it('quotes values that would otherwise parse as a non-string', () => {
    expect(yamlScalar('true')).toBe('"true"')
    expect(yamlScalar('1234')).toBe('"1234"')
    expect(yamlScalar('no')).toBe('"no"')
  })
})

describe('buildConfigYaml', () => {
  const answers: SetupAnswers = {
    node: 'app-1',
    interval: 30,
    agents: [
      { name: 'web', check: { kind: 'http', value: 'http://localhost:3000/health' }, restart: 'systemctl restart web' },
      { name: 'worker', check: { kind: 'process', value: 'worker' }, restart: false },
    ],
    webhookUrl: 'https://discord.com/api/webhooks/abc',
  }

  it('produces YAML that parses and satisfies the core schema', () => {
    const yaml = buildConfigYaml(answers, HB)
    const parsed = parseYaml(yaml)
    const cfg = Config.parse(parsed)
    expect(cfg.node).toBe('app-1')
    expect(cfg.heartbeat.url).toBe(HB)
    expect(cfg.heartbeat.interval).toBe(30)
    expect(cfg.agents).toHaveLength(2)
    expect(cfg.agents[0].checks[0]).toEqual({ http: 'http://localhost:3000/health' })
    expect(cfg.agents[0].restart).toBe('systemctl restart web')
    expect(cfg.webhook?.url).toBe('https://discord.com/api/webhooks/abc')
  })

  it('marks an alert-only agent (restart:false) with no restart key', () => {
    const yaml = buildConfigYaml(answers, HB)
    const parsed = parseYaml(yaml) as any
    expect(parsed.agents[1].restart).toBeUndefined()
    expect(yaml).toContain('alert-only')
  })

  it('omits the webhook block when no webhook was given', () => {
    const yaml = buildConfigYaml({ ...answers, webhookUrl: undefined }, HB)
    expect(yaml).not.toContain('webhook:')
    expect(() => Config.parse(parseYaml(yaml))).not.toThrow()
  })

  it('keeps teaching comments so the file stays hand-editable', () => {
    const yaml = buildConfigYaml(answers, HB)
    expect(yaml).toContain('# pulse.config.yaml — generated by `pulse init`')
    expect(yaml).toContain('after `pulse login`')
  })
})

describe('validateAnswers', () => {
  it('throws on an invalid webhook URL before anything is written', () => {
    const bad: SetupAnswers = {
      node: 'n',
      interval: 60,
      agents: [{ name: 'a', check: { kind: 'process', value: 'a' }, restart: false }],
      webhookUrl: 'not-a-url',
    }
    expect(() => validateAnswers(bad, HB)).toThrow()
  })
})

// ---------------------------------------------------------------------------
// A scripted fake Prompter: queue up answers, assert the flow asks for them.
// ---------------------------------------------------------------------------
function fakePrompter(script: {
  texts?: string[]
  selects?: number[] // index chosen per select() call
  multiselects?: number[][] // indices chosen per multiselect() call
  confirms?: boolean[]
}): Prompter {
  const texts = [...(script.texts ?? [])]
  const selects = [...(script.selects ?? [])]
  const multiselects = [...(script.multiselects ?? [])]
  const confirms = [...(script.confirms ?? [])]
  return {
    intro() {},
    note() {},
    outro() {},
    close() {},
    async text() {
      if (texts.length === 0) throw new Error('fake: ran out of text answers')
      return texts.shift()!
    },
    async select<T>({ options }: { options: SelectOption<T>[] }) {
      if (selects.length === 0) throw new Error('fake: ran out of select answers')
      return options[selects.shift()!].value
    },
    async multiselect<T>({ options }: { options: SelectOption<T>[] }) {
      if (multiselects.length === 0) throw new Error('fake: ran out of multiselect answers')
      return multiselects.shift()!.map(i => options[i].value)
    },
    async confirm() {
      if (confirms.length === 0) throw new Error('fake: ran out of confirm answers')
      return confirms.shift()!
    },
  }
}

describe('collectAnswers', () => {
  it('walks a single-agent http + restart flow', async () => {
    const p = fakePrompter({
      // node, agent-name, http-value, restart-value, webhook-value
      texts: ['app-1', 'web', 'http://localhost:3000/health', 'systemctl restart web', 'https://discord.com/api/webhooks/x'],
      // interval(60), check-kind(http), recovery(restart)
      selects: [1, 1, 0],
      // add another? no ; webhook? yes
      confirms: [false, true],
    })
    const answers = await collectAnswers(p, { hostname: 'fallback', platform: 'linux' })
    expect(answers.node).toBe('app-1')
    expect(answers.interval).toBe(60)
    expect(answers.agents[0]).toEqual({
      name: 'web',
      check: { kind: 'http', value: 'http://localhost:3000/health' },
      restart: 'systemctl restart web',
    })
    expect(answers.webhookUrl).toBe('https://discord.com/api/webhooks/x')
  })

  it('records an alert-only agent and no webhook', async () => {
    const p = fakePrompter({
      // node, agent-name, process-value
      texts: ['node-x', 'worker', 'worker-proc'],
      // interval(30), check kind(process=0), recovery(alert=1)
      selects: [0, 0, 1],
      // add another? no ; webhook? no
      confirms: [false, false],
    })
    const answers = await collectAnswers(p, { hostname: 'h', platform: 'linux' })
    expect(answers.node).toBe('node-x')
    expect(answers.interval).toBe(30)
    expect(answers.agents).toHaveLength(1)
    expect(answers.agents[0]).toEqual({
      name: 'worker',
      check: { kind: 'process', value: 'worker-proc' },
      restart: false,
    })
    expect(answers.webhookUrl).toBeUndefined()
    // and the whole thing validates + serialises
    expect(() => validateAnswers(answers)).not.toThrow()
  })

  it('loops to collect multiple agents', async () => {
    const p = fakePrompter({
      texts: ['n', 'a', 'a-proc', 'b', 'b-proc'],
      selects: [1, 0, 1 /* a: process, alert */, 0, 1 /* b: process, alert */],
      confirms: [true /* add another */, false /* stop */, false /* webhook */],
    })
    const answers = await collectAnswers(p, { hostname: 'h', platform: 'linux' })
    expect(answers.agents.map(a => a.name)).toEqual(['a', 'b'])
  })

  it('pre-fills agents from autodetection and skips manual entry', async () => {
    const detected = [
      { name: 'nginx', source: 'systemd' as const, check: { kind: 'command' as const, value: 'systemctl --user is-active nginx' }, restart: 'systemctl --user restart nginx' },
      { name: 'api', source: 'pm2' as const, check: { kind: 'process' as const, value: 'api' }, restart: 'pm2 restart api' },
    ]
    const p = fakePrompter({
      texts: ['host'], // just the node name
      selects: [1], // interval
      multiselects: [[0, 1]], // pick both detected services
      confirms: [false /* add manually? no */, false /* webhook? no */],
    })
    const answers = await collectAnswers(p, { hostname: 'h', platform: 'linux' }, { detectServices: async () => detected })
    expect(answers.agents.map(a => a.name)).toEqual(['nginx', 'api'])
    expect(answers.agents[0].check).toEqual({ kind: 'command', value: 'systemctl --user is-active nginx' })
    expect(() => validateAnswers(answers)).not.toThrow()
  })

  it('still forces one manual agent when detection finds nothing', async () => {
    const p = fakePrompter({
      texts: ['host', 'svc', 'svc-proc'],
      selects: [1, 0, 1],
      confirms: [false /* add another? no */, false /* webhook? no */],
    })
    const answers = await collectAnswers(p, { hostname: 'h', platform: 'linux' }, { detectServices: async () => [] })
    expect(answers.agents).toHaveLength(1)
    expect(answers.agents[0].name).toBe('svc')
  })
})

describe('runPostSetup', () => {
  const actions = (calls: string[]) => ({
    login: async () => { calls.push('login') },
    testHeartbeat: async () => { calls.push('hb'); return { authenticated: true, ok: true } },
    dryCheck: async () => { calls.push('check'); return [{ name: 'a', up: true }] },
    installService: async () => { calls.push('install'); return { installed: true, message: 'ok' } },
  })

  it('runs login, test heartbeat, dry check, and install when all confirmed', async () => {
    const calls: string[] = []
    await runPostSetup(fakePrompter({ confirms: [true, true, true, true] }), actions(calls))
    expect(calls).toEqual(['login', 'hb', 'check', 'install'])
  })

  it('skips every step when the user declines', async () => {
    const calls: string[] = []
    await runPostSetup(fakePrompter({ confirms: [false, false, false, false] }), actions(calls))
    expect(calls).toEqual([])
  })

  it('continues gracefully when login throws', async () => {
    const p = fakePrompter({ confirms: [true, false, false, false] })
    await expect(runPostSetup(p, {
      login: async () => { throw new Error('device code expired') },
      testHeartbeat: async () => ({ authenticated: false, ok: false }),
      dryCheck: async () => [],
      installService: async () => ({ installed: false, message: 'n/a' }),
    })).resolves.toBeUndefined()
  })
})
